"""
=============================================================================
backend/memory/memory_models.py
=============================================================================

WHAT THIS FILE DOES:
    Defines all the data structures (types, shapes, enums) that the memory
    system uses. Think of this as the "blueprint" or "contract" for what a
    memory looks like in Zytrix.

WHY THIS FILE EXISTS:
    In software engineering we separate DATA DEFINITIONS from BUSINESS LOGIC.
    This file only describes the shape of data — it never touches the database,
    network, or any external service. This is called the "Model" layer.

    Benefits:
    ─────────
    1. SINGLE SOURCE OF TRUTH: Every module imports from here. If you rename
       a field, you change it in one place and it propagates everywhere.

    2. TYPE SAFETY: Python's `dataclass` + `enum` give you IDE autocompletion
       and catch typos at development time, not at runtime.

    3. DECOUPLING: The database layer, repository, classifier, and manager
       all share the same data language without depending on each other.

WHY NOT USE PYDANTIC?
    Pydantic adds validation (e.g. "confidence must be between 0.0 and 1.0").
    For now, plain `dataclass` is simpler and dependency-free. The code is
    designed so you could swap to pydantic models in < 30 minutes.

EDUCATIONAL CONCEPT — ENUMS:
    An Enum (Enumeration) is a set of named, constant values. Instead of
    magic strings like "preference" scattered around your code, we use:
        MemoryCategory.PREFERENCE
    Benefits: no typos, autocomplete, and you can list all valid values.

=============================================================================
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


# =============================================================================
# ENUMERATIONS
# =============================================================================

class MemoryCategory(str, Enum):
    """
    WHAT: The type/category of a stored memory.

    WHY AN ENUM?
        Using an Enum prevents invalid values. You can't accidentally store
        category="prefrence" (typo). The Enum only allows these exact values.

    WHY `str, Enum`?
        Inheriting from `str` means the Enum values ARE strings. This makes
        SQLite storage and JSON serialization trivial — no `.value` needed
        in most contexts.

    FUTURE EXTENSION:
        Add new categories here without touching any other module. The
        classifier and repository will automatically support them.
    """
    PREFERENCE  = "preference"   # e.g. "My favourite IDE is VSCode"
    FACT        = "fact"         # e.g. "I graduate in 2026"
    REMINDER    = "reminder"     # e.g. "Remind me about my dentist appointment"
    ROUTINE     = "routine"      # e.g. "I usually code at night"
    PROJECT     = "project"      # e.g. "I'm building Zytrix"
    GENERAL     = "general"      # Catch-all for things that don't fit above


class MemorySource(str, Enum):
    """
    WHAT: WHERE a memory came from.

    WHY TRACK THE SOURCE?
        In production systems, data provenance (where data came from) is
        critical for debugging. Imagine you have a bug where wrong facts
        are stored — you need to know "did the user say this, or did the
        system infer it?"

    FUTURE EXTENSION:
        - IMPORTED: memories synced from another device or backup file
        - API: memories fetched from a web service
        - INFERRED: memories auto-generated by an LLM analyzing a conversation
    """
    CONVERSATION = "conversation"  # User said it directly in chat
    MANUAL       = "manual"        # Developer/admin inserted it directly
    SYSTEM       = "system"        # Zytrix itself generated this memory
    IMPORTED     = "imported"      # Loaded from a backup or external source


# =============================================================================
# DATA CLASSES
# =============================================================================
#
# EDUCATIONAL CONCEPT — DATACLASSES:
#     @dataclass is a Python decorator that auto-generates boilerplate like
#     __init__, __repr__, and __eq__ based on the field annotations.
#
#     Without @dataclass you'd write:
#         def __init__(self, id, category, key, ...):
#             self.id = id
#             self.category = category
#             ...
#     With @dataclass all of that is automatic.
#
#     field(default_factory=...) is used for mutable defaults like lists.
#     Using `= []` directly as a default would be a Python bug (shared state).

@dataclass
class MemoryItem:
    """
    WHAT: Represents a single piece of long-term memory about the user.

    This is the core unit of the memory system. Every fact, preference,
    or project the user mentions gets stored as a MemoryItem.

    FIELD EXPLANATIONS:
    ───────────────────
    key         : The "label" for the memory. Should be concise and consistent.
                  Example: "favourite_ide", "current_project", "graduation_year"
                  WHY: Consistent keys allow update detection (see MemoryRepository).

    value       : The actual content of the memory.
                  Example: "VSCode", "Zytrix", "2026"

    category    : One of MemoryCategory enum values.
                  WHY: Allows grouped retrieval and future category-based decay.

    confidence  : How certain we are this memory is accurate. Float 0.0 to 1.0.
                  Starts at classifier-assigned value. Increases when the user
                  repeats the same information.
                  FUTURE: Decay over time if memory hasn't been confirmed.

    importance  : How SIGNIFICANT this memory is. Float 0.0 to 1.0.
                  Separate from confidence — you can be confident about a
                  low-importance fact (e.g. "the weather was nice today").
                  WHY: Higher importance = more likely to be injected into
                  the prompt during retrieval.

    source      : One of MemorySource enum values.
                  WHY: Traceability — know where every memory originated.

    embedding_id: Placeholder for future vector embedding integration.
                  CURRENT: Always None (not used yet).
                  FUTURE: Store the ID of this memory's vector in ChromaDB/FAISS.
                  WHY NOW? Adding it to the schema today prevents a painful
                  database migration later. It costs nothing to store NULL.

    id          : Auto-assigned by the database (INTEGER PRIMARY KEY).
                  Optional here because new items don't have an ID yet.

    created_at  : Set once when the memory is first stored.
                  WHY: Useful for auditing, age-based decay, and debugging.

    updated_at  : Updated every time the memory changes.
                  WHY: Allows "most recently updated" sorting in retrieval.
    """
    key          : str
    value        : str
    category     : MemoryCategory
    confidence   : float = 0.8
    importance   : float = 0.5
    source       : MemorySource = MemorySource.CONVERSATION
    embedding_id : Optional[str] = None          # Placeholder — see FUTURE above
    id           : Optional[int] = None
    created_at   : datetime = field(default_factory=datetime.now)
    updated_at   : datetime = field(default_factory=datetime.now)


@dataclass
class ConversationMessage:
    """
    WHAT: A single message turn in a conversation session.

    WHY SEPARATE FROM MemoryItem?
        Conversation history is TEMPORARY. It serves immediate context
        for the LLM. Long-term memories are PERMANENT facts we want to
        remember forever. Mixing them creates technical debt because:

        - They have different query patterns (recent vs. keyword-based)
        - They have different retention policies (short vs. forever)
        - They have different schema needs (session_id matters for history,
          but a preference has no "session")

        Keeping them in separate tables and separate Python classes enforces
        this discipline at the type level.

    FIELD EXPLANATIONS:
    ───────────────────
    session_id  : Groups messages into one conversation session.
                  When Zytrix restarts, a new session_id is generated.
                  This lets us retrieve a full conversation for summarization.

    role        : "user" or "assistant" — same as the OpenAI/Groq message format.

    message     : The raw text content of the message.

    timestamp   : When this message was spoken/sent.

    id          : Auto-assigned by the database.
    """
    session_id  : str
    role        : str                            # "user" or "assistant"
    message     : str
    timestamp   : datetime = field(default_factory=datetime.now)
    id          : Optional[int] = None


@dataclass
class ConversationSummary:
    """
    WHAT: A condensed, human-readable summary of a past conversation session.

    WHY STORE SUMMARIES INSTEAD OF FULL HISTORY?
        Context windows are finite and expensive. A 2-hour conversation might
        have 200 messages. We cannot inject all of that into every LLM call.
        A summary compresses 200 messages into 5–10 bullet points that capture
        the key decisions, topics discussed, and outcomes.

        ANALOGY: Think of a daily standup meeting ("Yesterday I fixed the login
        bug, today I'm working on payments") vs. a full transcript of everything
        said the day before. The standup is far more useful for quick context.

    WHY A SEPARATE DATACLASS?
        Summaries and raw history have different shapes and are queried
        differently. Summaries are retrieved by recency; history is retrieved
        by session_id. Separate classes enforce this at the type level.
    """
    session_id  : str
    summary     : str
    created_at  : datetime = field(default_factory=datetime.now)
    id          : Optional[int] = None


# =============================================================================
# FUTURE EXTENSION POINTS
# =============================================================================
#
# TODO: MemoryFragment — for sub-sentence level granularity (future NLP parsing)
#
# TODO: UserProfile — for multi-user support. Each MemoryItem would gain a
#       `user_id` foreign key. Today's code uses a single implicit user.
#
# TODO: KnowledgeEdge — for knowledge graph representation. Stores a
#       (subject, predicate, object) triple, e.g. ("user", "prefers", "VSCode").
#
# TODO: MemoryCluster — for memory consolidation. Groups related MemoryItems
#       that refer to the same concept and merges them.
